### ISSUE TITLE
admin/adminUser 后台管理页面报错

### ISSUE THREAD

**Issue by NameWjp** [doramart/DoraCMS-SQL#16]
其他页面正常，这个页面打开报错，报错如下：

app-errors.js:9 Uncaught adminUser: Application 'adminUser' died in status LOADING_SOURCE_CODE: s.a.get is not a function
    at Module.56d7 (http://10.10.10.9:10003/static/adminUser/js/app.js:1:63388)
    at l (http://10.10.10.9:10003/static/adminUser/js/app.js:12:22600)
    at Object.0 (http://10.10.10.9:10003/static/adminUser/js/app.js:1:728)
    at l (http://10.10.10.9:10003/static/adminUser/js/app.js:12:22600)
    at Object.<anonymous> (http://10.10.10.9:10003/static/adminUser/js/app.js:12:22504)
    at Object.execute (http://10.10.10.9:10003/static/plugins/systemjs/4.1.0/extras/amd.min.js:1:599)
    at Object.declaration.execute (http://10.10.10.9:10003/static/plugins/systemjs/4.1.0/extras/named-exports.js:40:19)
    at i (http://10.10.10.9:10003/static/plugins/systemjs/4.1.0/system.min.js:4:3448)
    at t (http://10.10.10.9:10003/static/plugins/systemjs/4.1.0/system.min.js:4:3417)
    at http://10.10.10.9:10003/static/plugins/systemjs/4.1.0/system.min.js:4:3679

**Comment by NameWjp** [comment]
解决了，但不清楚为什么。。我把 adminUser 里的 mount 里的 console.log 给删除，重新打包，覆盖 dist 文件夹里的 adminUser，结果神奇的好了。。不太清楚是作者上传的 dist 有问题还是这个 console.log 的问题，之前没接触过 single-spa，感觉这玩意把复杂度提升了好一截，像上面这种报错有点无从下手...，因为这里报错的代码全是打包后的，完全不知道哪里有问题。。

**Comment by doramart** [comment]
可以使用调试模式来解决和发现问题，详见 https://www.doracms.com/backend/backstage/
